baseURL = 'https://rohimoz28.github.io'
languageCode = 'en-us'
title = 'Rohimoz28'
theme = 'PaperMod'
publishDir = "docs"

[cover]

[params.assets]
  disableFingerprinting = true

[params]
    ShowBreadCrumbs = true
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Categories'
    pageRef = '/categories/'
    weight = 20
  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags/'
    weight = 30


